name: Smoke

on:
  push:
  pull_request:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke test
        run: echo "smoke test passed"
